### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by looooo** [booya-at/paraBEM#2]
- [x] PYBIND 11 support
- [x] use independet python-eigen!
- [X] outsource laplace kernel
- [ ] use laplace kernels
- [ ] use shared pointers for panelvectors
- [ ] unittests
- [x] rename package to paraBEM
- [x] upload to conda

**Comment by looooo** [comment]
won't happen
